name: Run Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Altere para a versão que seu bot usa

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run bot
      run: |
        python bot.py  # Altere para o nome do seu arquivo principal
